<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'Predis' => array($vendorDir . '/predis/predis/lib'),
    'Pimple' => array($vendorDir . '/pimple/pimple/lib'),
    'Libcast' => array($baseDir . '/project/utilities/QueueSrc'),
);
